stages:
  - validate
  - plan
  - apply
  - ansible
  - destroy

include:
  - project: 'developerdurp/yml-templates' 
    ref: 'main'
    file: 
      - 'terraform.yml'
      - 'ansible.yml'

plan production:
  extends: .plan production
  before_script:
  - echo "token = \"$token\"" >> terraform.tfvars 

apply:
 extends: .apply
 variables:
 before_script:
  - echo "token = \"$token\"" >> terraform.tfvars 

destroy:
 extends: .destroy
 before_script:
   - echo "token = \"$token\"" >> terraform.tfvars 
