stages:
  - validate
  - plan
  - apply
  - ansible
  - destroy

before_script:
  - echo "token = \"$token\"" >> terraform.tfvars 
  - terraform output kubeconfig

include:
  - project: 'developerdurp/yml-templates' 
    ref: 'main'
    file: 
      - 'terraform.yml'
      - 'ansible.yml'

plan production:
  extends: .plan production
  allow_failure: true
  artifacts:
    when: on_failure
    paths:
      - $CI_PROJECT_DIR

apply:
  extends: .apply

destroy:
  extends: .destroy
