kube-prometheus-stack: 

  alertmanager:
    fullnameOverride: alertmanager
    enabled: true
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/auth-response-headers: Authorization
        external-dns.alpha.kubernetes.io/hostname: alertmanager.durp.info
        nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://oauth.durp.info/oauth2/start?rd=https://$host$request_uri$is_args$args        
      hosts:
        - alertmanager.durp.info
      paths: 
        - /
      tls: 
      - secretName: alertmanager-tls
        hosts:
        - alertmanager.durp.info
  
  grafana:
    enabled: true
    fullnameOverride: grafana
    forceDeployDatasources: false
    forceDeployDashboards: false
    defaultDashboardsEnabled: true
    defaultDashboardsTimezone: utc
    serviceMonitor:
      enabled: true
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/hostname: grafana.durp.info
        kubernetes.io/ingress.class: nginx
      hosts:
        - grafana.durp.info
      paths: 
        - /
      tls: 
      - secretName: grafana-tls
        hosts:
        - grafana.durp.info      

# Disable control plane metrics
  kubeEtcd:
    enabled: false
  
  kubeControllerManager:
    enabled: false
  
  kubeScheduler:
    enabled: false
