apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgCgyl6I4YZ4Bo1IRot87nZxRJ3jtNsRgAntyFEOADxgtd6hw7GwtksoZzhfiL+NvyqUR2JaqK/WH0xGxfXYpuKS2jcPaSS87kqqWTkEOGfXC0zeTfqMErBwK7EYuQAcn/K71U2GmOutzivOrzSC+9FH1u8aSs2w8azP9PIRjPi2h+BmqnBMP8gtE85l+E7Bo9GZpZ62u1cJLc23gZQEeQWhHOqGvcVuvKSA/1Ecfs9L5dkgS5pP0ZwIHZ3qeOz49hXYzLMP/MVh9oz4uk40PTVGHhUFmLlbRpL9jj6x3Nx0BKbEUaNN61kVXDFpK37hrrckDoMBX5OBlefKO4PYHeDRQxrcPaxQqQczpVylY6eWzE+ZwqmKpBivXRZNk4MBJ2zGfjb3wFOGapuHnvJmCwer/R8/NCxkdgjhMPZHMd0kmp96L0kAbaIJqTxkuq/UgMTVmfZC1xTizkr+2PSAJqgDWfgg4jLdQKON8JveluU0dNG8S2mnjE90PPaihMzdc0K8XkWoviP1SW/xPRhTWoO12C6lUt8pv5aX6tQElz8Z8dLaRtGsYZyEBOYaNWNKhmyMeuIhhmNSd0sw4zzjPvW4xOiNYoftGqLzB05ByC+vQ1JTe51rd80FvV1FcfJWE0SixULzIKnuqb8DP4iY/Jy0xNBKDOrnWQywQhkO+aFm/C5TyQFZvID7/JZ/zz7o2LefJcxezep7rVCa2koLEpzUFg==
    CF_API_KEY: AgAs1oH5mhWw7CoKq5WsJQpsvH7iPXNOBw7EmJaMyN9JignHv7Ll6v0ZsJnen/XxVeZBWS3qZzrrqT5e97tPjOsxYhxz6kPKiUXr9DUndiT4kf0tb7fkwAuwrobFyz6W7gdzFKeTS3TDN4Rj1r52PlsBJN1do6UoE8iHnk6xU9OwjJyvI1QTa4mr353sH/UQO3dZ8NzwMCZ9Lybatsw6I9YX7vWXX6Kz9ZR2ESP//0erx41KHKWp+nxfV8FEm5w1KvICgP5zDJxS0TpYti+v/px+giB85XAs/R9DBZptAM0IIx6AnGmvbiY/KNCBbrr2Qs7/V5b5nU5hDjEItlAMQUzxhWX3uzuNAS8lcI3jrdWLnIAnr8bWCp8ovRsqxhXZUPbGFcTWTWN4di580gfzYNEHdgxUzFmwCE1SXVynSFMUEUlG0B8wZm7h3UgtbQM5n9tsi/gKbIfosG4TljroXsCwj22zYr89iGfM0d2DZmEIq4K2ZT9hrSgGSNBGa+hQ5cCclcbCyX+kXlt2iswPdJL1tTdAEwSfxFmWOWv3DWxmtF2UCiicRTyZXFYX8KmT5ci/Y++qp0mx+ITca6pjgGfzrC0Plf44JTw0IyV9SOM3/jv4FG+kxjWoIpQnsfgJIkZyZy+D8/e+B90L+ql0RZ3UZv2FqdTG9WNSqUOpES067NbdyqKyB37we/f3Ke9R4fz5OVfXHCXQcU5nUnpaxQB3mN8wEIKpTiMLlrQ0vxunSVpGw40x1oDq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: external-dns
