apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgASfCgvzG8d1dNzGYHPQNUZtk/SfmjEppAt5ZdLmgOehmj25sAUkOUqTwTMcot/KwXAaYhzw6mB6jpYFCeZPQ8lB/TBQGH50E82F4oYEsV5b4/ik5P0tvUtGESsWalnEW+qJqt9FsyE4YHZ2yXHlhA0fY6+/fO6Q8gzF62Mf5ZinVIerkyjb/xBMPWU8HWmsWJ7E8OkjrzY3yspCR3U0aib+G5rygilIDR9KKr6Go29rJTTgF3+pcB0D238RhGwlG/Q5o0b4/TeMd8feGjVVJLl3Y2xByCifMbiVSq4/lM7p05xLlv1hX2vDy0+mOAc/FSRu9jNoDdmCJW/CFOSvUBjGKt3JyX9K0gjVjb2mP8QJK6QCMHrodci710p8UkQcTuUDjtjn3nB1JKK678joCWYp68xwyQVLE/NkGyWxz+JiZXqdzfZ4br1Q0OTe25LLCxEWw3NekUyVEz7nv74JwuKj1P/cbMkTg1lLRyWD+cj6UDccu8wJKhGlAO69fxumFaZTtALBTdsYnPQaZ6gkQqkI11gW2EfcqQZxbR3JOAeTYzLtB9a2gFG+CGMIzy8IFA2KCkoFpbYs90NnDCfc/WHCq+WISuqzpmH/1PWA+kZheG7bHHUpx5hgeqks3bynd4srOdYsvn+UFnzCZVZ53fnzLmY5SeIjWN0IndnX2jhTyi/42QrHmto/mUKNJwlWDseT+oNH7s8ckNYmJUmtzTLLCBdVCXY+1poe3yi/epTCmFX8uPtP6kY
    cloudflare_api_token: AgAK5wx60gfBi5HAG22EUxru+0VvO67oNm7C/3mOroKU1KsxhxzghQG3rChat1oIqjcvu57im6st/XZ7yYqPnFM+4BLWmUWdWDZosRu7oi5f14vVWWsytzsm+5TknFq/igvI5iTyFic/7xxkTXSuCOndCH87lUNSSKAlBBlFLsUv2UyziWM7eutPhp3I55Y7gu07uoVzx7714FxKSYoRyI04Ulp25kwtLZbf6V4JDfgFfKLHkGJ0Okdl64FN5RnmBRRhQ972Rt1eEGaPa+qCG4Y62mnrOKbcgRvEInDY2okz3zbgYhcddkYju//Q2rAifv/05MTIwgEsBbVwbNM4diGf38BBKNFZ2YmHh/AUPjSIoI4mDfvskiNrohU4BOIJoGxph6qi0tpIGDdGEt4SszkcVfk42BcSOKXredM6LFCHxkWvBDsgSl01e9rVWbkYfLcEbJoQLvxv4wfqfILVZb77wgZp/J9w/FXO4rT8LUCeo1Mp4F1HhqHlDNQclTBUKDft6/nCkoYdH0G+bcZnitNMdNbRfHDnze9KvZgIS7TuWW2ZPQaF7sPRPm6B1RX4R7JXQCg484NiYQxvLLN1PdD93iaX8/31EfaQwIToHTmsUXMGYQCKBkCNJiErAVbwYUeWxUhVOeqyCiyzDlKdILj41bmD33TkSwS4V6dVXYNVur1fjyVxdOOvyRoRu6o1CJmCeZqbU0VWBPexwqM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns