apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: external-dns
spec:
  encryptedData:
    CF_API_EMAIL: AgAx3pPD0Fd6zT7JqsDAhsB5vtRSRoVXh+JaOdh5KVUXcjOMA5uE0aY9xxi04s42TmDMIwybaRqZhPWlbQKp7Ar1jgyIYqaLgiJn/d4qQGcs9Gy4HA3a/GMHXef3zH2TfgpAA2MSNhFKYDAU8YOnhaHF8Q66U+n5/v2w/NVeRMObENZqDJb0HncOtIPunl9oJzupfsJd7UYLly/KyTpYO02tl7s7/j6BZ8a+ciqMlliz6FqlqZcmh0CdSuubE1V2MnNSitMrODAR5QskPuwdu9F35TqpJgeR1UM4MR2xb4Z5a0ffFx1voUadXdqFQSIKG0zTNKmvhxciUuf/MnMiZ6cqFsnbwasjIq0ki8kS8kaXTwYX4I0GjjoQpom5DRd9KfrcSi0COUmyVlawHPovz4CxfOg92+8PBQqGm8Xhocxyy8oC9kSvMjvLFvL1yrc6XwbAM2Xm9gsXQYYjTnAXamBbp31mWIlpX/2J+uYSuOo/hCv6yghhHbTCsNs2Cb9KjNxcaVkOPnpO9/qC+LFFJ+qspIqH1kQecyx3SEsnBLRdud+wU0+mi7MmugPnRp1s0bS9KM2ONd+KoyUVVWoLCpQZ7n6Jw0gGUtcop6P263v8OIdBzeTDQalLjf458R6vV5rqlgkFB2ZLup3EOHwwvnYCnWKeEqReKnpVo6bpu7u4hy2JTSBbVrFykfNv/JqaKLwQLBLQmBP6dfSf52njrQceQQ==
    CF_API_KEY: AgA5Zbcra7fUBGcsoCk37dbGjO5nDYkW2EzgybOO7on8yvwHSWmgZ6PGPLtBguv05VpfaBvuD0ToWNxcjrPT/Ul/ax4gYdkFcopT2CG4BBOBSaS+SjxeGW6w+9lFo+anxugCvW5duo+3iLV526qSfUBlT8OU7KixDIs+D+bBzfw0iVtMZ8m/9yrAzuBg4EKWQrYpHriWrrtl5zgkEO26gOeqk7+QhK2VfE9hfYMYk5nDSMHhSiSzONrbdiVewTvA52VIIn4l1tRbHNrrbEJdjrpdoVbQSgZa/2+3lBieUPi2G4jZQzExRTofg2uZY+bJd1hPw1yb4AhhgES2e7wBGYFUWb9WIvVAtpQZzjSENbtsCop9GlnVfyJSSX9UZVypshhfZt4BM3fUAjJNCF9UdFsl/zhYrXCws4AMnPlwahW8y+5a8D9FAVUrI+VCbU+N/TaXd6jX3yk3kcZUFV3SELOOIAagoCQLNDu+jhuS83t0OWp3plymcK6rjgZEnDZPqT585dBfvJhdDvq7w5Dx+WHiyXwjY2m4LOp79TTkQ/GNwg3lrdY5EDy9CrmWGCP9opFQij9GTm+xVbOIVzaro5ovemAJVH2wetW5MoNLMhUOZHOqgJd/xf2MXxl0Luhw+41kLAbOLi39WXZjY+0efcKLLUxVFq3jXcuZY4N99WEO46vWIY3NY1QXmtCi7lD+rQPY1GYad5qIxzb8PlJbkYm8A/6pQ6Fk/4p4YbW5hHr4S/4+dv/vQhnf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: external-dns
