apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_key: AgCWCkSH+XJd3dHDk5d1ZGBOC6D8WG7w01OyA189SxXzQqTzrGOr0yE+ctUlpnATQi2hc6VOKJ01SSH4c7SpjdxnHu19PTOuS0jNOnteDmzk1hnSiVWKPFDN0A7pb0vOQc+Y9GP5zw7r69wpbmgUuDTYIL/YWjzgzb1LZmL80i/dmIcQZFx87By+A33YTEMBNG4HV7Pj4CIBuGC0PtgEe5B5XyR2JA7VMcaEH2F+eELodHuUgrn9oxgxbX/XkXrd2nqWBBlAtCUS+xUyejwsJjGbaxf0yMRHVpSL7tPmPNsa4OISsMNZVgYmReaqhGZN6o6eBcClQnQbDzrqZUdOUEdUnOkfOETmxsH5PvoIDc9BzRwK1uBJPmOvQsdfZvfED39bWvYHxlh8nGvtKijIkNWrDMt1mVolVuQsE1BzM1od5VkyaE8cNgC41Kbr8ExJBrDT1+mbrDBt/wscCdWXzSy9q+tG2t5hLo9hA4w2gA6ksNgHg971Y4T0dpfFa3NRxV+/Bb+WpqeVjHsdwu4nWz9oEJv90cOVlMFUYjtaYmvue5q8oSGVYNZQkvwSJuFcaTihdt2g67sAuZpEwmshSDO3I4wIUj4cw6XoAgi6Fvre8R6jMucBcArT+zDiXxZZimIASsp0KlgG69YVEqGKmbq11oQsQD3ypnX1qOabd43+7HT5Aef6UC2TWYPvkxVHu7ahhXXwaz/wKcmMB7aemso6wcF4dDHqLYfm6jDPQeIK/hs3Dd7g2M0+
    cloudflare_api_token: AgCh0idEMScz6GU9GmSM37wx9hgCbetSjJZs+muIEQ0AMJIV4gErtjNvoqmS2GNv+8mt1npHXUZdxxxKra02qYyt+fRCMrt8riqMSvbT+yslaZpsRYi4L/txAXZn5cexFCAVgZ7comtDnFHqBzQejV4NFwmvZl9acsTPm6S2wOeBEklzP5a6iun7HzEl1fmR1wh+2VjgmXXEdI3EeSrxgPkRW1OPXowgI84eRrY7Z2MEFEknzMJG+Qn3y32xqL4AQ+6Tht66E1KNhNbZmDngU0zCwGXGmMq+m2sTEGgSZEV6/UWlAhZfslKDWgJzYNvyViDsQtiGXmDtHkBdJT9h3k3Nmg2+U84am74zTiA7iNfaBDItZp6dqyYGIB0TXMhDYHv/ooScI1y3KqUnrZxvjC6o9GP4c88DJC5y8pBeT/ZJsg4gvxBJu1VkyI3UfF7TOWr3BGLOoDwMtISEvtpAhIdJ9TBpcdQnTcUID6ELnAKnEpiuce1ogmHQfyDWxQytcw0E3Gjvta6uV+jkG97NdzStNxYEzxKwJh5c0hgZDsTyNi2VYUwoycKi1zAHejpaNJxzUCeuJfkEb/VFDevQFaIKzTVS/w99i7dwm28sjYutS0e+qIOjZyvf/9KnoZA6WU2kynoD5eZAGuAiv1joPNK8H150kFW19k/gfJyYqVBVQ8tA5LWLzu/vBrpFFh4BfJisXuTSqOEdKfL8rg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
