apiVersion: v2
name: authentik
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: authentik
  repository: https://charts.goauthentik.io/
  version: 2022.9.0
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 15.7.6
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.16.2
- name: common
  repository: https://library-charts.k8s-at-home.com
  tags:
  - bitnami-common
  version: 2.x.x
