apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    admin-password: AgAx+pgOkWMjzOSZTt5XGLgYh78yyYlSa3CHgWb4fPpnqkTOJojli99aIgMQ8HukigwJa8QymRiWlrr0JS2B/pvr6EcYs7JQC5sA1uqLnBp6GL6x712KWwaqFvplVBR5YCkVlAnQiioVZKmsflR5MH7Ue6/P6CgBea+gkxyeiuXHMSPWdEmt7N9QJ5yRctmNPNLO6TlKb/GePtAiQVatcLYDlQ4bRNns4vlS48vqBa9NE+7hZhyKMAZvH5iFg77mhtROUhKMN8gsUoDGFtVkljkjqAgu+1mtpDbEh8EHkSZ/MNE0X8KY7a1/8sxJgdtcn1fq+P2vNP3kFCfeveOEkojIDtwXMPmzpiTcLCNROY4UIsuuchhBQY0h8AcncJo6bYYEWHhkEdeEyrQDYcZnmgJ1BCxaIb0EyPi4P3oMd1Wan4rKZBY6OvLKkAAY/jQjibgSArG44K2FBzYL1GMV0NlzNoZsx1QZFZp9XPZBLKUoCxs/Xkv5KzaEtIirFTwQHUzkUlsZSFmLbdNnqDvxu+7K+TdY0uXtHijBrDYysTdM9AokRfGIjLmok6G58AGZa0dOLeacrRtBY3yyge0ZnQsd6BCJ08GM22SkC/uzGDLZr/4Giv0tL37pFIML6zoY4BeR3fgIlVgDHOoNfzbQ11NUjkkghA7lNfhp8oqS8SHhVCcl9Yo7uRgDSQV4MwUbtaLpWhvmRBb2gsBNIC8jvFof
    admin-user: AgAE0mWK/SvZJdoUWxpiRZYnfV+Vd6EI+eeut5ibBFE2bLXLkdXkYWGycNnbUZblYGqKNqKgcWXcLKmUEloyz+4yyP3vajhXv6Y37ZnawDUwTSXauLFvFeoGQsbnQXZzSAkINOodytSuhk+Lghs12tmwLQ5PuySbawO5VxWw4Cl1Wyg+xDsR90HDUZ8XDBXgPS8nlnQrj447+9aERmuuEGv+NDfB+ZPLZR0tQeIbT7hJEeH4JSfc5WCCGdcSvji3tJ/qwYHnUCPNHfUqB7p3OBqBjmmBvfkWjLCkBHMLBtSFEFZ1fSDCzA9YhQfONPb3NPSfupH4/XDOO5sf7aTiFNinebRz2mC0xxq1YgZkZXrPzI1JPkaf4FupT529t9vC0wV9QrRdAfdBgbB6UfKg3r+wEwr/bDKhGVPOYs+dEDHbYk9FKwDWh7+gRFpKxwuqErcne6vDE0oefr5NO/eANuC0F5mNlAkrhBUUFofi/ic1WTfbeSEQrYnr9yUHFdw6jnJ5CltL3xsw1HGv2koa423jdpB0GnCuzdkeRO7i44qDu8noz4ewiLgR7P8j9kNuL3jfipL1pRSJ5t8Y5GxzQxDhJITtMZPbZvIe9atAsaOgD/up4BD8h1xQDnq/oaRZ3JquaxI8OP7uQv8N6PilWQmzkJbmIPkLepuwAwvIyoqyu8ORepFN+m+RxfJeNyjvCvPj7iNXaee9KA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: kube-prometheus-stack
