apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: oauth-credentials
  namespace: kube-prometheus-stack
spec:
  encryptedData:
    admin-password: AgBfn+QVpYMiDlMpovzzypFOOANRSAHBEafWGmireDKGeidJTOkMzR22mwWwxPqGWxUQvwaRjDc9Itev3nvkwGIdkzqjlHrYD5obO9XTGNsCk+bS37YICPfELY1U/wdFmbTsCurT0Ev7ghb93LcZYIc/OrpufbwUzHPBcbgMO5ktnzR0u7ADhI3216/sTQpJbrMCmyFx7FYy4LOlCEZts2RwyAg0wSvcJFxpTO71IdjXHhiZ8VJSbbMCXmMOK9HPNS4u5yeIFs5tssFggc6Y9cMaNCPxHumaWiiJkVZqKemPfJyiT1T5L530X7jIhvJtCXMRjP1lxl2EqwOTTzsLQQ5H08LTDPkRBucYB6KovBZ1Qx2jUWnupNHHhb+9OdlRtQGNjTj5XbrlrsUtedBmhCMswnFoFQ1IMEBsKiPHMG9U7u8gxPChHSwBNkdwOcx/rsCjayYaU9vs1JJATcH9Tsv8KKP/adIlsDJJr3IKFG0AXRwMVc1nmlGmGBx+DzqE8sEE8JWIiNZi6wEV+PX03leKZRt4ooFOJGLKX/E70KJ5XO2dCXYMtPd+E27hdfCPn+JHFVfnTX7Ui2xiMl2O9v6QhLbVNYtV8yoHJiTatpezgFU+KbwkGDaM3IoFFyzzPGem6tEhJ8qK1pLpqi+g8bAWi2wTLVNAJeP22onm9stNtfzxTcHTAEUYBospHlqVICMng1clQB4g8HU/p+meTBeI
    admin-user: AgAgpNYjqQh1+wGHUX8wqAbjI7jBBu5wCNfbEWWJRjDq4QqTlqE0lEYnNM3jRCUiMnhNeAZY2eKahGRrhdmgWxl3hLjIDgH4WkTXKqKlyuidN74EWRJWi1I+WXWF5qaQLDst1if4HchfNYLjy8Mh4fT6p3xQZ7yx+R4ikUN66x2BMYc00Yg48so08GqIXdKnc4Fp72kgEims0e6OGDHdf4aMZhxDipjFmtQPCpu/egqZxZORBSIlm0xrUgPmCAVBm5ehpcrpE/i/ouHX/a85MKpmzTHVJmcfTlSac3LUdKkZZMZxhxpMPHf8E+Lw8jugm1EsdbKh22DKoY46LxtctrmxxBwWnouValfkrpwqF/i9i/cTnyYv3Qa3L1cff/xPyd1Cy26ocqWhLBPAj42fSWRcy7z7J2ZHzqzGBUBGhO3gU7k4ZQbNXuOW7Wqw0JTGKp3vnV3fYG2s6tZbhvUVkSg5SbkqKm2EyfFSZQRqSs8PyPHuU2eQ+SIrbbI+FPvcnZEXIzsFzCx8OZD4AO8A/PHvdShc95cKfZbzSMHwIOlLyQuTIZcW+T12Cd3v7OWDvBGMx1sYaq/z21ZUm00JP2xodVRxnTIi+tMZOX0OSTXAXGBkS7witENdRSeJumSZsduaPOrSrxCMMLqsujuITGXy0tcMv5DqJ/uS6kel0s9GYjMpE8LTATo/SXHC18jMNnq56Vvc9usO1Q==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: oauth-credentials
      namespace: kube-prometheus-stack
