apiVersion: v2
name: metrics-server
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: metrics-server
  repository: https://charts.bitnami.com/bitnami
  version: 6.2.0